services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: asset
      POSTGRES_PASSWORD: asset
      POSTGRES_DB: assetdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - asset-net

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - asset-net

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - asset-net

networks:
  asset-net:
    driver: bridge
